name: Pull data from DVC remote


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
on:
  push:
jobs:
  pull-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python  -version: '3.8'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install DVC
        run: |
          pip install dvc dvc_s3
      - name: Configure DVC
        run: |
          dvc remote add myremote s3://udacity-api-mlops-bucket
      - name: Pull data from DVC remote
        run: dvc pull
