name: Test with pytest and flake 8

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "requirements.txt"
    - name: Install DVC
      run: |
        pip install dvc dvc_s3
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Configure DVC
      run: |
        dvc remote add myremote s3://udacity-api-mlops-bucket
    - name: Pull data from DVC remote
      run: |
        dvc pull
    - name: Start API server
      run:  |
        python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload &
        sleep 3  # Wait for the server to start
    - name: Test with pytest
      run: |
        pytest -c test/pytest.ini
    - name: Stop server
      run: |
        kill $(lsof -t -i:8000)  # Stop the server process
        sleep 3  # Wait for the server to stop completely
        
    - name: Continuous deploy to Heroku
      run: |
        git push heroku main
